name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Ajoute cette ligne

      - name: Build
        run: ./gradlew build  # Adapte cette commande si tu utilises un autre système de build.

      - name: Run tests
        run: ./gradlew test  # Assure-toi que cette commande correspond à tes tests.
